#!/usr/bin/python3

"""
A simple script for display the content of .bin files via the Pillow imaging
library. This script expects DISPLAY to be set to a valid X11 output.
"""

import sys
import argparse

from PIL import Image


def show(image, size):
    data = image.read()
    width, height = size
    if len(data) != width * height // 8:
        raise ValueError(f"Size of .bin file does not match the specified "
                         f"size; {len(data)} != {width * height // 8} "
                         f"({width} x {height} / 8)")
    img = Image.new('1', size)
    for offset, byte in enumerate(data):
        for bit in range(8):
            y = (offset * 8) // width
            x = (offset * 8 + bit) % width
            # The shift is reversed here because the output is little-endian
            img.putpixel((x, y), (255, 0)[(data[offset] >> (7 - bit)) & 0b1])
    img.show()


def main(args=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        'image', type=argparse.FileType('rb'), default=sys.stdin.buffer,
        help="The .bin file to display")
    parser.add_argument(
        '--width', type=int, default=64,
        help="The assumed width of the image")
    parser.add_argument(
        '--height', type=int, default=64,
        help="The assumed height of the image")
    config = parser.parse_args()

    show(config.image, (config.width, config.height))


if __name__ == '__main__':
    main()
